services:
    kwc_newsletter.command.newsletter:
        class: KwcNewsletter\Bundle\Command\Newsletter
        arguments: [@kwc_newsletter.model.newsletters]
        tags:
            - { name: 'console.command' }

    kwc_newsletter.command.import_subscribers:
        class: KwcNewsletter\Bundle\Command\ImportSubscribers
        arguments: [@kwc_newsletter.importer.parser.csv, @kwc_newsletter.importer.subscriber_factory, @kwc_newsletter.importer.excluder.manager]
        tags:
            - { name: 'console.command' }

    kwc_newsletter.command.start_runner:
        class: KwcNewsletter\Bundle\Command\StartRunner
        arguments: [@kwc_newsletter.model.newsletters, @kwc_newsletter.model.newsletter_runs]
        tags:
            - { name: 'console.command' }

    kwc_newsletter.command.combine_category_subscribers:
        class: KwcNewsletter\Bundle\Command\CombineCategorySubscribers
        arguments: [@kwc_newsletter.model.newsletters, @kwc_newsletter.model.subscribers_to_categories, @kwc_newsletter.model.newsletter_subscriber_logs]
        tags:
            - { name: 'console.command' }

    kwc_newsletter.command.delete_newsletter_subscribers:
        class: KwcNewsletter\Bundle\Command\DeleteNewsletterSubscribers
        arguments: [@kwc_newsletter.model.subscribers]
        tags:
            - { name: 'console.command' }
