kwc_newsletter.subscribers_api:
    resource: "@KwcNewsletterBundle/Controller/SubscribersApiController.php"
    type: annotation
kwc_newsletter.open_api_subscribers:
    resource: "@KwcNewsletterBundle/Controller/OpenApiSubscribersController.php"
    type: annotation
kwc_newsletter.open_api_categories:
    resource: "@KwcNewsletterBundle/Controller/OpenApiCategoriesController.php"
    type: annotation
